# Site settings
title: Void Legion
description: > # this means to ignore newlines until "baseurl:"
  Void's sleeping... come back later.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.voidlegion.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
